### PR TITLE
Rundeck integration into pan-fca

### PR DESCRIPTION
**Pull request by mdrobniu**
**What Changes are taking place?**
This change incorporates rundeck into the pan-fca container. 
The rundeck implementation is generic to the master branch (It does not have any influence on the current processes and procedures that are described in the documentation)
This PR does not contain the ported Example Files (Azure and AWS) into the Rundeck projects. 

Rundeck allows the user to plan ansible and terraform jobs, execute them in a controlled way reducing the probability of a human mistake.

### CODE REVIEW

**Comment by mdrobniu** [comment]
FYI @ancoleman

**Comment by ancoleman** [comment]
Let's see some corresponding documentation to go along with this.

**Comment by mdrobniu** [comment]
Check out https://github.com/PaloAltoNetworks/pan-fca/pull/25/files#diff-bdb5863a000379042f6eafc28e016124 for the documentation.

**Comment by ancoleman** [comment]
The problem is this document only explains how to turn on rundeck. If you could provide more documentation on how rundeck is integrated with the framework, and how to customize it for the user's needs.

**Comment by mdrobniu** [comment]
Acknowledged

**Comment by torstenstern** [comment]
@mdrobniu we need a documentation like this https://github.com/PaloAltoNetworks/pan-fca/tree/master/FCA_Lab.
But we talked already about this.

**Comment by torstenstern** [comment]
@mdrobniu is there any update from your side? If not we will close this PR

**Comment by mdrobniu** [comment]
This is still being processed.

**Comment by torstenstern** [comment]
@mdrobniu we have to close this case then we have to clean up the stuff. You can create an new one when everything is ready

**Pull request closed without merging**
